housing_connectivity_initiative:
  outputs:

    dev:
      type: postgres
      threads: 2
      host: theory.bcgov
      port: 5433
      user: ods_admin_user
      pass: ${ODS_PASSWORD}
      dbname: odsdev
      schema: public

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

rrs_xnrs_data_processing:
  outputs:

    dev:
      type: postgres
      threads: 2
      host: theory.bcgov
      port: 5433
      user: ods_admin_user
      pass: ${ODS_PASSWORD}
      dbname: odsdev
      schema: app_rrs1

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

fta_data_processing:
  outputs:

    dev:
      type: postgres
      threads: 2
      host: theory.bcgov
      port: 5433
      user: ods_admin_user
      pass: ${ODS_PASSWORD}
      dbname: odsdev
      schema: fta_replication

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

ods_fta_data_processing:
  outputs:

    dev:
      type: postgres
      threads: 2
      host: theory.bcgov
      port: 5443
      user: dlh_ods_mapping_user
      pass: ${ODS_PASSWORD}
      dbname: lhousedev
      schema: fdw_ods_rrs_replication

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev
